import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  ar: {
    searchPlaceholder: 'بحث عام...',
    searchByNationalId: 'بحث برقم القومي...',
    searchByProperty: 'بحث بالعقار أو الوحدة...',
    welcome: 'مرحباً بك',
    dashboard: 'الرئيسية',
    addProperty: 'إضافة عقار',
    linkOwner: 'ربط المالك',
    addAppeal: 'تسجيل طعن',
    addExemption: 'تسجيل إعفاءات',
    calcTax: 'حساب وتقدير الضريبة',
    collect: 'تسجيل سداد',
    users: 'إدارة المستخدمين',
    logs: 'سجل النظام',
    verdict: 'قرارات اللجان',
    reports: 'التقارير الإدارية',
    language: 'اللغة',
    logout: 'تسجيل خروج',
    login: 'تسجيل الدخول',
    mainSystem: 'نظام الضرائب العقارية',
    fees: 'رسوم التقديم: 100 ج.م',
    notifications: 'الإشعارات',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    assistant: 'المساعد الذكي',
    noNewNotifications: 'لا توجد إشعارات جديدة حالياً',
    save: 'حفظ',
    cancel: 'إلغاء',
    editProfile: 'تعديل الملف الشخصي',
    back: 'رجوع',
    emailAlerts: 'تنبيهات البريد الإلكتروني',
    compactView: 'عرض مضغوط',
    darkMode: 'الوضع الليلي',
    settingsSaved: 'تم حفظ الإعدادات',
    browserAlerts: 'تنبيهات المتصفح',
    profilePhoto: 'صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'حذف الصورة',
    name: 'الاسم',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    usernamePasswordRequired: 'اسم المستخدم وكلمة المرور مطلوبان',
    usernameExists: 'اسم المستخدم موجود بالفعل',
    changesSaved: 'تم حفظ التغييرات بنجاح',
    currentUser: 'مستخدم حالي',
    guest: 'زائر',
    taxSystem: 'نظام الضرائب',
    taxManagementSystem: 'نظام إدارة الضرائب',
    employeeLogin: 'تسجيل دخول الموظفين',
    enter: 'دخول',
    forgotPassword: 'نسيت كلمة المرور؟',
    resetPassword: 'إعادة تعيين كلمة المرور',
    verificationCode: 'رمز التحقق',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    sendVerification: 'إرسال رمز التحقق',
    backToLogin: 'العودة لصفحة تسجيل الدخول',
      collectionPageTitle: 'تسجيل سداد ضريبي',
  receiptNoLabel: 'رقم الإيصال (Receipt No)',
  paymentMethodLabel: 'طريقة الدفع',
  paymentAmountLabel: 'مبلغ الدفع (ج.م)',
  paymentDateLabel: 'تاريخ السداد',
  unitOwnerDataTitle: 'بيانات الوحدة والمالك',
  pendingInstallmentsTitle: 'الأقساط المستحقة (الرجاء اختيار قسط للدفع)',
  noPendingInstallments: 'لا توجد أقساط مستحقة حالياً (قد يكون النظام لم يولدها بعد).',
  fullyPaid: 'لا توجد أقساط مستحقة',
  readyToPay: 'جاهز للدفع',
  receiptTitle: 'إيصال سداد الضريبة',
  receiptNoText: 'رقم الإيصال:',
  unitIdText: 'رقم الوحدة:',
  ownerNameText: 'اسم المالك:',
  addressText: 'العنوان:',
  paidAmountText: 'المبلغ المدفوع:',
  methodText: 'طريقة الدفع:',
  dateText: 'تاريخ السداد:',
  installmentText: 'القسط:',
  printReceiptBtn: 'طباعة الإيصال',
  backToHomeBtn: 'العودة للرئيسية',
  enterCashierNumber: 'اكتب رقم الكاشير...',
  dueDate: 'تاريخ الاستحقاق',
  amountLabel: 'المبلغ (ج.م)',
  selectInstallment: 'اختيار',
  totalAnnualTax: 'إجمالي الضريبة السنوية',
  cancel: 'إلغاء',
  searchPlaceholder: 'أدخل رقم الوحدة للبحث السريع واضغط Enter...',
  searchingUnit: 'جاري البحث عن الوحدة...',
  useSearchAbove: 'استخدم خانة البحث أعلاه لإدخال رقم الوحدة',
  unitDataWillAppear: 'سيتم عرض بيانات الوحدة والأقساط المستحقة هنا.',
  allInstallmentsPaid: 'جميع الأقساط المسجلة لهذه الوحدة تم دفعها',
  noUnitFound: 'وحدة غير موجودة برقم:',
  unitNotApproved: 'هذه الوحدة لم توافق عليها الإدارة بعد ولا يمكن تسجيل سداد أو طباعة فاتورة.',
  selectInstallmentFirst: 'الرجاء اختيار القسط المراد دفعه أولاً من الجدول',
  paymentSuccess: 'تم تسجيل السداد بنجاح. يمكنك طباعة الإيصال الآن.',
  operationFailed: 'فشلت العملية: ',
  unexpectedError: 'حدث خطأ غير متوقع',
  searchError: 'حدث خطأ في البحث',
  primaryOwner: 'المالك الأساسي',
  unitId: 'رقم الوحدة',
  taxYear: 'السنة الضريبية',
  totalDue: 'إجمالي المستحق',
  },
  en: {
    searchPlaceholder: 'General search...',
    searchByNationalId: 'Search by National ID...',
    searchByProperty: 'Search by property or unit...',
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    addProperty: 'Add Property',
    linkOwner: 'Link Owner',
    addAppeal: 'Register Appeal',
    addExemption: 'Register Exemption',
    calcTax: 'Calculate Tax',
    collect: 'Collect Payment',
    users: 'Users Management',
    logs: 'System Logs',
    verdict: 'Verdicts',
    reports: 'Administrative Reports',
    language: 'Language',
    logout: 'Logout',
    login: 'Login',
    mainSystem: 'Real Estate Tax System',
    fees: 'Submission Fee: 100 EGP',
    notifications: 'Notifications',
    settings: 'Settings',
    profile: 'Profile',
    assistant: 'Assistant',
    noNewNotifications: 'No new notifications right now',
    save: 'Save',
    cancel: 'Cancel',
    editProfile: 'Edit Profile',
    back: 'Back',
    emailAlerts: 'Email alerts',
    compactView: 'Compact view',
    darkMode: 'Dark mode',
    settingsSaved: 'Settings saved',
    browserAlerts: 'Browser alerts',
    profilePhoto: 'Profile photo',
    changePhoto: 'Change photo',
    removePhoto: 'Remove photo',
    name: 'Name',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    phone: 'Phone Number',
    usernamePasswordRequired: 'Username and password are required',
    usernameExists: 'Username already exists',
    changesSaved: 'Changes saved successfully',
    currentUser: 'Current user',
    guest: 'Guest',
    taxSystem: 'Tax System',
    taxManagementSystem: 'Tax Management System',
    employeeLogin: 'Employee Login',
    enter: 'Login',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    verificationCode: 'Verification Code',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    sendVerification: 'Send Verification Code',
    backToLogin: 'Back to Login Page'
  }
};

export const LanguageContext = createContext();

const phraseTranslations = {
  'نظام الضرائب العقارية': 'Real Estate Tax System',
  'تسجيل دخول الموظفين': 'Employee Login',
  'اسم المستخدم': 'Username',
  'كلمة المرور': 'Password',
  'دخول': 'Login',
  'الرئيسية': 'Home',
  'إضافة عقار': 'Add Property',
  'ربط المالك': 'Link Owner',
  'طعن ضريبي': 'Tax Appeal',
  'طلب إعفاء': 'Exemption Request',
  'المهام اليومية': 'Daily Tasks',
  'حساب الضرائب': 'Tax Calculation',
  'التحصيل والسداد': 'Collection and Payment',
  'تسجيل دفع جديد': 'Register New Payment',
  'الاعتمادات النهائية': 'Final Approvals',
  'التقارير المالية': 'Financial Reports',
  'طعون': 'Appeals',
  'إعفاءات': 'Exemptions',
  'لوحة التحكم': 'Dashboard',
  'إدارة المستخدمين': 'User Management',
  'سجلات المراقبة': 'Audit Logs',
  'تسجيل خروج': 'Logout',
  'مستخدم حالي': 'Current user',
  'زائر': 'Guest',
  'نظام الضرائب': 'Tax System',
  'نظام إدارة الضرائب': 'Tax Management System',
  'لوحة التحكم الموحدة (System Dashboard)': 'Unified System Dashboard',
  'نظرة عامة على المباني والوحدات والنشاطات الضريبية': 'Overview of buildings, units, and tax activity',
  'المباني': 'Buildings',
  'الوحدات': 'Units',
  'الإعفاءات': 'Exemptions',
  'الطعون': 'Appeals',
  'آخر العمليات على النظام': 'Latest System Activity',
  'لا توجد سجلات عمليات حديثة.': 'No recent activity logs.',
  'التاريخ والوقت': 'Date and Time',
  'الموظف': 'Employee',
  'المستخدم': 'User',
  'الإجراء': 'Action',
  'الجهة': 'Entity',
  'التفاصيل': 'Details',
  'سجل النظام الشامل': 'Full System Log',
  'الوحدات الضريبية': 'Tax Units',
  'رقم الوحدة': 'Unit Number',
  'نوع الوحدة': 'Unit Type',
  'العنوان': 'Address',
  'المالك': 'Owner',
  'الحالة': 'Status',
  'لا توجد وحدات.': 'No units.',
  'غير معروف': 'Unknown',
  'مدفوع': 'Paid',
  'جديد': 'New',
  'بانتظار المدير': 'Waiting for Manager',
  'نوع الإعفاء': 'Exemption Type',
  'رقم العقار': 'Property Number',
  'تاريخ الطلب': 'Request Date',
  'المرفق': 'Attachment',
  'الإجراءات': 'Actions',
  'لا توجد طلبات.': 'No requests.',
  'قيد المراجعة': 'Under Review',
  'مقبول': 'Accepted',
  'مرفوض': 'Rejected',
  'مغلق': 'Closed',
  'الملاك': 'Owners',
  'الاسم': 'Name',
  'الرقم': 'Number',
  'الصفة': 'Role',
  'التاريخ': 'Date',
  'لا توجد بيانات.': 'No data.',
  'غير محدد': 'Not specified',
  'مالك': 'Owner',
  'مستأجر': 'Tenant',
  'سبب الطعن': 'Appeal Reason',
  'تاريخ التقديم': 'Submission Date',
  'لا توجد طعون.': 'No appeals.',
  'بانتظار الرسم': 'Waiting for Fee',
  'قيد اللجنة': 'In Committee Review',
  'لا يمكن الحذف': 'Cannot delete',
  'حفظ': 'Save',
  'إلغاء': 'Cancel',
  'رجوع': 'Back',
  'الإعدادات': 'Settings',
  'تنبيهات البريد الإلكتروني': 'Email alerts',
  'عرض مضغوط': 'Compact view',
  'الوضع الليلي': 'Dark mode',
  'اللغة': 'Language',
  'تم حفظ الإعدادات': 'Settings saved',
  'الملف الشخصي': 'Profile',
  'صورة الملف الشخصي': 'Profile photo',
  'تغيير الصورة': 'Change photo',
  'حذف الصورة': 'Remove photo',
  'البريد الإلكتروني': 'Email',
  'رقم الهاتف': 'Phone Number',
  'الإشعارات': 'Notifications',
  'لا توجد إشعارات جديدة حالياً': 'No new notifications right now',
  'تمت إضافة مستخدم جديد إلى النظام': 'A new user was added to the system',
  'يوجد طلبات معلقة تحتاج مراجعة': 'There are pending requests that need review',
  'تم تحديث سياسة الإشعارات': 'Notification policy was updated',
  'منذ 5 دقائق': '5 minutes ago',
  'منذ ساعة': '1 hour ago',
  'منذ يوم': '1 day ago',
  'منذ يومين': '2 days ago',
  'غير مصرح لك بالدخول': 'Access Denied',
  'عذراً، ليس لديك الصلاحيات الكافية للوصول إلى هذه الصفحة.': 'Sorry, you do not have enough permissions to access this page.',
  'العودة للخلف': 'Go Back',
  'جمهورية مصر العربية': 'Arab Republic of Egypt',
  'وزارة المالية - مصلحة الضرائب العقارية': 'Ministry of Finance - Real Estate Tax Authority',
  'نظام تحصيل وتقدير الضرائب': 'Tax Collection and Assessment System',
  'اختيار مواطن / مالك': 'Select Citizen / Owner',
  'ابحث بالاسم أو الرقم القومي...': 'Search by name or national ID...',
  'الرقم القومي': 'National ID',
  'الهاتف': 'Phone',
  'الإيميل': 'Email',
  'النوع': 'Type',
  'اختيار': 'Select',
  'اعتباري': 'Legal Entity',
  'فرد (طبيعي)': 'Individual',
  'لا توجد نتائج مطابقة للبحث.': 'No matching search results.',
  'اختيار وحدة ضريبية': 'Select Tax Unit',
  'ابحث عن الوحدة (العنوان أو الرقم)...': 'Search for a unit (address or number)...',
  'الضريبة التقديرية': 'Estimated Tax',
  'لا توجد نتائج': 'No results',
  'بحث واختيار عقار': 'Search and Select Property',
  'اسم المالك': 'Owner Name',
  'الوحدات': 'Units',
  'المساحة': 'Area',
  'لا توجد عقارات مسجلة': 'No registered properties',
  'جديد': 'New',
  'عرض كل الإشعارات': 'View all notifications',
  'تم إضافة عقار جديد بنجاح': 'A new property was added successfully',
  'تمت الموافقة على طلب إعفاء سابق': 'A previous exemption request was approved',
  'تنبيه النظام: برجاء مراجعة الطلبات المعلقة': 'System alert: please review pending requests',
  'تعديل طلب': 'Edit Request',
  'تعديل طلب ضريبي': 'Edit Tax Request',
  'تعديل طعن ضريبي': 'Edit Tax Appeal',
  'تعديل طلب إعفاء': 'Edit Exemption Request',
  'تحديث': 'Update',
  'رقم قومي المالك': 'Owner National ID',
  'رقم قومي للممول': 'Taxpayer National ID',
  'رقم الوحدة (Unit ID)': 'Unit ID',
  'أدخل الرقم القومي...': 'Enter national ID...',
  'مثال: 1024': 'Example: 1024',
  'المبلغ المتنازع عليه': 'Disputed Amount',
  'اكتب تفاصيل الاعتراض...': 'Write appeal details...',
  'رفع المستندات': 'Upload Documents',
  'محضر / أدلة': 'Report / Evidence',
  'حفظ التعديلات': 'Save Changes',
  'حفظ الطلب': 'Save Request',
  'طلب إعفاء': 'Exemption Request',
  'نوع الإعفاء': 'Exemption Type',
  'اختر نوع الإعفاء...': 'Select exemption type...',
  'الوحدة السكنية الأساسية': 'Primary Residential Unit',
  'إعفاء ذوي الإعاقة': 'Disability Exemption',
  'ملكيات وقفية': 'Endowment Properties',
  'جمعيات خيرية': 'Charities',
  'رقم المادة القانونية': 'Legal Article Number',
  'مثال: مادة 37': 'Example: Article 37',
  'تاريخ بداية الإعفاء': 'Exemption Start Date',
  'تاريخ نهاية الإعفاء': 'Exemption End Date',
  'اتركه فارغاً إذا كان الإعفاء دائم': 'Leave empty if the exemption is permanent',
  'عقد ملكية / صورة البطاقة': 'Ownership Contract / ID Copy',
  'يمكنك رفع ملف بصيغة PDF أو صورة. الحد الأقصى 5 ميجا.': 'You can upload a PDF or image. Maximum size is 5 MB.',
  'ربط المالك / المستأجر': 'Link Owner / Tenant',
  'بيانات الربط': 'Link Data',
  'ابحث واختار العقار من القائمة...': 'Search and select a property from the list...',
  'بحث واختيار': 'Search and Select',
  'اسم المالك': 'Owner Name',
  'اختر الوحدة': 'Select Unit',
  'الدور / رقم الشقة': 'Floor / Apartment Number',
  'نوع العلاقة القانونية': 'Legal Relationship Type',
  'تاريخ بداية العلاقة': 'Relationship Start Date',
  'تاريخ نهاية العلاقة': 'Relationship End Date',
  'تأكيد الربط': 'Confirm Link',
  'إدارة الموظفين': 'Employee Management',
  'إضافة موظف': 'Add Employee',
  'قائمة الموظفين': 'Employee List',
  'تعديل موظف': 'Edit Employee',
  'حفظ التغييرات': 'Save Changes',
  'سجل نظام التدقيق (Audit Logs)': 'Audit Logs',
  'تحديث': 'Refresh',
  'لا توجد سجلات حالياً.': 'No logs currently.',
  'اسم الموظف': 'Employee Name',
  'نوع الإجراء': 'Action Type',
  'الجدول المتأثر': 'Affected Table',
  'تفاصيل العملية': 'Operation Details',
  'مكتب المدير العام': 'General Manager Office',
  'لوحة متابعة تشغيلية مبنية على الملفات والمدفوعات الحالية': 'Operational dashboard based on current files and payments',
  'الاعتمادات': 'Approvals',
  'التقارير': 'Reports',
  'قرارات معلقة': 'Pending Decisions',
  'تحصيل فعلي': 'Actual Collection',
  'أقساط مستحقة': 'Due Installments',
  'طعون وإعفاءات': 'Appeals and Exemptions',
  'ملفات تحتاج قرار': 'Files Needing Decision',
  'فتح قائمة الاعتماد': 'Open Approval List',
  'لا توجد ملفات معلقة حاليًا': 'No pending files currently',
  'الضريبة': 'Tax',
  'ينتظر توقيع': 'Waiting for Signature',
  'آخر عمليات التحصيل': 'Latest Collections',
  'لا توجد مدفوعات مسجلة بعد': 'No payments recorded yet',
  'الإيصال': 'Receipt',
  'المبلغ': 'Amount',
  'إجمالي المستحق': 'Total Due',
  'إجمالي التحصيل': 'Total Collected',
  'المتبقي للتحصيل': 'Remaining to Collect',
  'بانتظار اعتماد المدير': 'Waiting for Manager Approval',
  'نسبة التحصيل': 'Collection Rate',
  'توزيع الضريبة حسب نوع الوحدة': 'Tax Distribution by Unit Type',
  'لا توجد وحدات مسجلة': 'No registered units',
  'أداء الموظفين': 'Employee Performance',
  'تصدير التقرير PDF': 'Export PDF Report',
  'القسم': 'Department',
  'المهام المنجزة': 'Completed Tasks',
  'الدقة': 'Accuracy',
  'تفاصيل': 'Details',
  'ممتاز': 'Excellent',
  'يحتاج متابعة': 'Needs Follow-up',
  'مكتب الاعتمادات والقرارات': 'Approvals and Decisions Office',
  'اعتماد تقديرات الوحدات، قرارات اللجان، وطلبات الإعفاء': 'Approve unit assessments, committee decisions, and exemption requests',
  'تقديرات المراجع': 'Reviewer Assessments',
  'لا توجد ملفات': 'No files',
  'نوع/دور': 'Type/Floor',
  'توقيع': 'Sign',
  'قرارات اللجان': 'Committee Decisions',
  'لا توجد قرارات معلقة': 'No pending decisions',
  'رقم القضية': 'Case Number',
  'قرار اللجنة': 'Committee Decision',
  'الضريبة الأصلية': 'Original Tax',
  'المبلغ المقترح': 'Proposed Amount',
  'اعتماد': 'Approve',
  'طلبات الإعفاء': 'Exemption Requests',
  'لا توجد طلبات إعفاء معلقة': 'No pending exemption requests',
  'رقم الطلب': 'Request Number',
  'تحميل': 'Download',
  'لا يوجد': 'None',
  'قبول': 'Accept',
  'رفض': 'Reject',
  'اعتماد تقدير': 'Approve Assessment',
  'اعتماد قرار لجنة': 'Approve Committee Decision',
  'اعتماد إعفاء': 'Approve Exemption',
  'القرار': 'Decision',
  'قبول الطعن': 'Accept Appeal',
  'رفض الطعن': 'Reject Appeal',
  'ملاحظات اللجنة': 'Committee Notes',
  'رفض التوصية': 'Reject Recommendation',
  'توقيع وتنفيذ': 'Sign and Execute',
  'بيانات الوحدة والمالك': 'Unit and Owner Data',
  'إجمالي الضريبة السنوية': 'Total Annual Tax',
  'الأقساط المستحقة': 'Due Installments',
  'الرجاء اختيار قسط للدفع': 'Please select an installment to pay',
  'تاريخ الاستحقاق': 'Due Date',
  'المبلغ (ج.م)': 'Amount (EGP)',
  'لا توجد أقساط مستحقة حالياً': 'No installments are currently due',
  'نموذج الدفع': 'Payment Form',
  'رقم الإيصال': 'Receipt Number',
  'اكتب رقم الكاشير...': 'Enter cashier number...',
  'طريقة الدفع': 'Payment Method',
  'نقدي': 'Cash',
  'تحويل بنكي': 'Bank Transfer',
  'مبلغ الدفع': 'Payment Amount',
  'تاريخ السداد': 'Payment Date',
  'تأكيد دفع القسط': 'Confirm Installment Payment',
  'إيصال سداد الضريبة': 'Tax Payment Receipt',
  'المبلغ المدفوع': 'Paid Amount',
  'القسط': 'Installment',
  'طباعة الإيصال': 'Print Receipt',
  'العودة للرئيسية': 'Back to Home',
  'ج.م': 'EGP',
  'م²': 'm²',
    // --- كلمات صفحة تسجيل إعفاء المفقودة ---
  'اختر': 'Select',
  'كود الوحدة المختار:': 'Selected Unit Code:',
  'سكن أساسي': 'Primary Residence',
  'إعاقة': 'Disability',
  'جمعيات': 'Charities',
  'المرجع القانوني': 'Legal Reference',
  'سبب الإعفاء': 'Exemption Reason',
  'تاريخ الإعفاء': 'Exemption Date',
  'البداية': 'Start',
  'النهاية': 'End',
  'ملاحظات': 'Notes',
  'كود:': 'Code:',
  'الدور:': 'Floor:',
  'المساحة:': 'Area:',
  'الاستخدام:': 'Usage:',
  'دور': 'Floor',
  'ملف': 'File',
  'قسط مدفوع': 'Paid Installment',
  'ربط المالك بالعقار': 'Link Owner to Property',
  'بيانات المالك': 'Owner Details',
  'أدخل الرقم القومي أو ابحث...': 'Enter National ID or search...',
  'مرتبط بـ': 'Currently linked to',
  'وحدة حالياً، سيتم إعادة استخدام بياناته': 'unit(s), their data will be reused',
  'يمكنك اختيار مالك موجود أو تسجيل مالك جديد': 'You can select an existing owner or register a new one',
  'أدخل اسم المالك': 'Enter owner name',
  'أدخل عنوان المالك': 'Enter owner address',
  'انقر على بحث لاختيار العقار...': 'Click search to select property...',
  'تم تحميل': 'Loaded',
  'وحدة — اختر منها أدناه': 'unit(s) — select from below',
  'هذا العقار لا يحتوي على وحدات مسجّلة': 'This property has no registered units',
  'الوحدات والحصص': 'Units and Shares',
  'الوجهة': 'Destination',
  'نوع العلاقة': 'Relationship Type',
  'الحصة %': 'Share %',
  'تاريخ البداية': 'Start Date',
  'تاريخ النهاية': 'End Date',
  'اختر الوحدة...': 'Select unit...',
  'إضافة وحدة أخرى': 'Add Another Unit',
  'توزيع متساوٍ': 'Even Distribution',
  'مجموع الحصص:': 'Total Shares:',
  'تأكيد الربط': 'Confirm Link',
  'اختيار العقار': 'Select Property',
  'بحث...': 'Search...',
  'تعذّر تحميل العقارات': 'Failed to load properties',
  'تعذّر تحميل الوحدات': 'Failed to load units',
  'لا توجد عقارات مطابقة': 'No matching properties',
    // --- كلمات صفحة تسجيل الطعن المفقودة ---
  'إضافة': 'Add',
  'ابحث عن الربط الضريبي المراد الطعن عليه': 'Search for the tax link to appeal on',
  'جاري البحث...': 'Searching...',
  'كود الوحدة': 'Unit Code',
  'عنوان العقار': 'Property Address',
  'السنة الضريبية': 'Tax Year',
  '✓ الربط الضريبي المختار': '✓ Selected Tax Link',
  'تاريخ تقديم الطعن': 'Appeal Submission Date',
  'تفاصيل وسبب الطعن': 'Appeal Details and Reason',
  'عقار #': 'Property #',
  'تم ربط المالك بالوحدة/الوحدات بنجاح ✔': 'Owner successfully linked to unit(s) ✔',
  'يجب إدخال الرقم القومي، الاسم، الهاتف، العنوان، واختيار العقار أولاً': 'National ID, Name, Phone, Address, and Property selection are required',
  'يجب اختيار عقار أولاً': 'Property must be selected first',
  'يجب اختيار الوحدة لكل سطر قبل الربط': 'Please select a unit for each row before linking',
  'لا يمكن تكرار نفس الوحدة في أكثر من سطر': 'Cannot select the same unit in multiple rows',
  'نسبة الحصة لكل وحدة يجب أن تكون بين 0 و 100': 'Share percentage for each unit must be between 0 and 100',
  'يجب إدخال تاريخ البداية لكل وحدة': 'Start date is required for each unit',
  'تاريخ النهاية يجب أن يكون بعد أو يساوي تاريخ البداية': 'End date must be after or equal to start date',
  'نسيت كلمة المرور؟': 'Forgot Password?',
  'نسيت كلمة المرور': 'Forgot Password',
  'إعادة تعيين كلمة المرور': 'Reset Password',
  'أدخل البريد الإلكتروني': 'Enter email address',
  'إرسال رمز التحقق': 'Send Verification Code',
  'تم إرسال رمز التحقق إلى بريدك الإلكتروني': 'Verification code sent to your email',
  'رمز التحقق': 'Verification Code',
  'رمز التحقق غير صحيح': 'Invalid verification code',
  'كلمة المرور الجديدة': 'New Password',
  'تأكيد كلمة المرور الجديدة': 'Confirm New Password',
  'تغيير كلمة المرور': 'Change Password',
  'تم تغيير كلمة المرور بنجاح! جاري التوجيه لصفحة الدخول...': 'Password changed successfully! Redirecting to login...',
  'البريد الإلكتروني غير مسجل في النظام': 'Email is not registered in the system',
  'كلمتا المرور غير متطابقتين': 'Passwords do not match',
  'العودة لصفحة تسجيل الدخول': 'Back to Login Page',
  'الرجاء إدخال الرقم القومي': 'Please enter National ID',
  'الرجاء البحث عن الممول بالرقم القومي أولًا': 'Please search for taxpayer by National ID first',
  'الرجاء البحث عن المالك بالرقم القومي أولًا': 'Please search for owner by National ID first',
  'الرجاء اختيار الوحدة': 'Please select a unit',
  'الرجاء إدخال المبلغ المتنازع عليه': 'Please enter the disputed amount',
  'الرجاء إدخال سبب الطعن': 'Please enter the reason for appeal',
  'تم حفظ طلب الطعن بنجاح': 'Appeal request saved successfully',
  'تم تسجيل العقار وربط بياناته بنجاح! رقم العقار:': 'Property successfully registered and linked! Property ID:',
  'تم العثور على المالك بنجاح': 'Owner found successfully',
  'لم يتم العثور على المالك': 'Owner not found',
  'طلب إعفاء جديد': 'New Exemption Request',
  'الرجاء إدخال تاريخ الإعفاء': 'Please enter exemption date',
  'الرجاء اختيار نوع الإعفاء': 'Please select exemption type',
  'تم حفظ طلب الإعفاء بنجاح': 'Exemption request saved successfully',
  'تسجيل عقار جديد': 'Register New Property',
  'بيانات المبنى والمالك': 'Building and Owner Details',
  'المحافظة': 'Governorate',
  'المركز': 'Center',
  'اسم الشارع': 'Street Name',
  'الحي / المنطقة الضريبية': 'Neighborhood / Tax Zone',
  'سنة البناء': 'Build Year',
  'وصف العقار': 'Property Description',
  'ملكية فردية للعقار بالكامل (فيلا / منزل)': 'Single ownership of the entire property (Villa / House)',
  'سيتم تسجيل العقار كوحدة ضريبية واحدة (لا داعي لتقسيم شقق)': 'The property will be registered as a single tax unit (no need to divide apartments)',
  'سيتم تسجيل العقار كمبنى يحتوي على عدة وحدات (شقق/محلات)': 'The property will be registered as a building containing multiple units (apartments/shops)',
  'الوحدات داخل المبنى': 'Units inside building',
  'كود / رقم الوحدة': 'Unit Code / Number',
  'نوع الوحدة': 'Unit Type',
  'الدور': 'Floor',
  'الاستخدام': 'Usage',
  'متاح': 'Available',
  'إضافة وحدة': 'Add Unit',
  'حفظ العقار': 'Save Property',
  'عقد ملكية / صورة البطاقة': 'Ownership Contract / ID Copy',
  'يمكنك رفع ملف بصيغة PDF أو صورة. الحد الأقصى 5 ميجا.': 'You can upload a PDF or image. Maximum size 5 MB.',
  'الرجاء اختيار قسط للدفع': 'Please select an installment to pay',
  'لا توجد أقساط مستحقة حالياً': 'No installments are currently due',
  'نموذج الدفع': 'Payment Form',
  'رقم الإيصال': 'Receipt Number',
  'طريقة الدفع': 'Payment Method',
  'نقدي': 'Cash',
  'تحويل بنكي': 'Bank Transfer',
  'مبلغ الدفع': 'Payment Amount',
  'تاريخ السداد': 'Payment Date',
  'تأكيد دفع القسط': 'Confirm Installment Payment',
  'إيصال سداد الضريبة': 'Tax Payment Receipt',
  'طباعة الإيصال': 'Print Receipt',
  'العودة للرئيسية': 'Back to Home',
  'أهلاً بك في نظام المساعدة الذكي. كيف أساعدك اليوم؟': 'Welcome to the Smart Assistant system. How can I help you today?',
  'شكراً لسؤالك': 'Thank you for your question',
  'مساعد النظام (': 'System Assistant (',
  'متصل الآن للرد على استفساراتك': 'Online now to answer your questions',
  'اكتب استفسارك هنا...': 'Type your question here...',
  'إرسال': 'Send',
  'هل أنت متأكد من حذف طلب الإعفاء هذا؟': 'Are you sure you want to delete this exemption request?',
  'فشل الحذف': 'Delete failed',
  'هل أنت متأكد من حذف طلب الطعن هذا؟': 'Are you sure you want to delete this appeal request?',
  'تم حذف الطعن بنجاح': 'Appeal deleted successfully',
  'تفضيلات الواجهة': 'Interface Preferences',
  'اختاري شكل وتجربة الاستخدام المناسبة.': 'Choose the layout and experience that suits you.',
  'تفعيل تنبيهات المتصفح عند توفرها.': 'Enable browser notifications when available.',
  'تقليل المسافات لعرض بيانات أكثر.': 'Reduce spacing to show more data.',
  'تبديل ألوان النظام للوضع الليلي.': 'Toggle system colors to dark mode.',
  'النسخ الاحتياطي والتصدير': 'Backup and Export',
  'احتفظي بنسخة كاملة أو صدّري الجداول الأساسية.': 'Keep a full backup or export key tables.',
  'يحتوي على بيانات النظام المحفوظة محليًا.': 'Contains system data saved locally.',
  'إنشاء نسخة': 'Create Backup',
  'تم إرسال توصية اللجنة للمدير': 'Committee recommendation sent to manager',
  'فشلت العملية': 'Operation failed',
  'معلقة للجنة': 'Pending Committee',
  'معروضة على المدير': 'Presented to Manager',
  'إصدار توصية': 'Issue Recommendation',
  'تم الإرسال': 'Sent',
  'توصية لجنة الطعن': 'Appeal Committee Recommendation',
  'اسم المستخدم أو البريد الالكتروني': 'Username or Email',
  // --- كلمات صفحة تعديل الإعفاء المفقودة ---
  'رقم:': 'No.:',
  'تم تحديث طلب الإعفاء بنجاح!': 'Exemption request updated successfully!',
  // ============================================= //
  // --- كلمات الداشبورد الجديدة (ثابتة) --- //
  // ============================================= //
  'في انتظار اللجنة': 'Pending Committee',
  'إضافة عقار جديد': 'Add New Property',
  'تسجيل عقار + ربط المالك تلقائياً': 'Register property + Auto-link owner',
  'ربط مالك إضافي': 'Link Additional Owner',
  'إضافة شريك ملكية أو تحديث المالك': 'Add ownership partner or update owner',
  'تقديم طعن ضريبي': 'Submit Tax Appeal',
  'اعتراض على القيمة أو تقدير الضرائب': 'Objection to value or tax assessment',
  'طلب إعفاء ضريبي': 'Tax Exemption Request',
  'وحدات سكنية أساسية / ذوي إعاقة': 'Primary residential units / Disability',
  'الطلبات المعلقة (تحتاج متابعة)': 'Pending Requests (Need Follow-up)',
  'القرارات الصادرة (الأرشيف)': 'Issued Decisions (Archive)',
  'الملاك المسجلون': 'Registered Owners',
  'العقارات والوحدات': 'Properties and Units',
  'يُعرض آخر 5 طلبات — ابحث بالاسم أو الرقم القومي لعرض المزيد': 'Shows last 5 requests — Search by name or National ID to show more',
  'بحث باسم المالك أو الرقم القومي...': 'Search by owner name or National ID...',
  'كود / رقم الوحدة': 'Unit Code / Number',
  'السند القانوني': 'Legal Document',
  'الحالة النهائية': 'Final Status',
  'لا توجد قرارات صادرة حالياً': 'No issued decisions currently',
  'ابحث باسم المالك أو رقمه القومي ثم اختره للاطلاع على وحداته': 'Search by owner name or National ID, then select to view their units',
  'ابدأ بكتابة اسم المالك في خانة البحث': 'Start typing the owner name in the search box',
  'سيظهر لك اقتراحات، اختر المالك للانتقال إلى صفحة وحداته': 'Suggestions will appear, select the owner to go to their units page',
  'ابحث بكود الوحدة لعرض بياناتها أو اترك البحث فارغاً لعرض كل الوحدات': 'Search by unit code to view its data, or leave empty to view all units',
  'بحث بكود / رقم الوحدة...': 'Search by unit code / number...',
  'الوحدة:': 'Unit:',
  'رقم المبنى': 'Building Number',
  'التشطيب': 'Finishing',
  'لا توجد وحدة مطابقة لكود البحث': 'No unit matches the search code',
  'لا توجد وحدات مسجلة حالياً': 'No units registered currently',
  'سكني': 'Residential',
  'تجاري': 'Commercial',
  'متوفر': 'Available',
  'مشغول': 'Occupied',
  'طعن': 'Appeal',
  'إعفاء': 'Exemption',
    'المساحة (م²)': 'Area (m²)',
  'حذف': 'Delete',
  'مثال: 1 أو A1': 'Example: 1 or A1',
  'شقة': 'Apartment',
  'المساحة الكلية للعقار (م²)': 'Total Property Area (m²)',
  'مثال: 250': 'Example: 250',
  'ملاحظة':'Note',
  'جاري الحفظ...': 'Saving...',
  'حدث خطأ أثناء الحفظ': 'Error occurred while saving',
  'بيانات المالك لا تُسجّل في هذه المرحلة. سيتم ربط المالك لاحقاً من صفحة "ربط المالك" مع الاسم، الرقم القومي، الهاتف، والإيميل.': 'Owner data is not registered at this stage. The owner will be linked later from the "Link Owner" page with Name, National ID, Phone, and Email.'
  ,'تعديل العقار و الملاك': 'Edit Property & Owners',
  'رقم العقار:': 'Property No.:',
  'مجموع الملكية:': 'Total Ownership:',
  '1. بيانات الموقع': '1. Location Data',
  '2. الملاك الحاليون': '2. Current Owners',
  'لا يوجد ملاك مرتبطين حالياً': 'No owners currently linked',
  'إضافة مالك جديد': 'Add New Owner',
  'الملكية مكتملة (100%)': 'Ownership is complete (100%)',
  'النسبة الحالية:': 'Current percentage:',
  'بيع': 'Sale',
  'ميراث': 'Inheritance',
  'هبة': 'Gift',
  'تم تحديث بيانات العقار بنجاح!': 'Property data updated successfully!',
  'وحدة': 'Unit',
  'العقار':'property',
  'دور': 'Floor',
  'مثال: دور 3 أو شقة 12': 'Example: Floor 3 or Apartment 12',
  'حدث خطأ أثناء الربط': 'An error occurred during linking',
  'بحث':'Search',
    'هل أنت متأكد من حذف هذا المالك؟ لا يمكن التراجع عن هذا الإجراء.': 'Are you sure you want to delete this owner? This action cannot be undone.',
  'تم حذف المالك بنجاح': 'Owner deleted successfully',
  'فشل حذف المالك، حاول مرة أخرى': 'Failed to delete owner, please try again',
  'هل أنت متأكد من حذف ربط هذه الوحدة بهذا المالك؟': 'Are you sure you want to unlink this unit from this owner?',
  'لم يتم العثور على بيانات المالك': 'Owner data not found',
    'تعذر تحميل الربطات الضريبية': 'Failed to load tax links',
  'لا توجد نتائج مطابقة للبحث': 'No matching results found',
  'إجمالي النتائج:': 'Total results:',
  'صفحة': 'Page',
  'من': 'of',
  'اسم المالك، الرقم القومي، أو كود الوحدة...': 'Owner name, National ID, or Unit code...',
  'السنة الضريبية (اختياري)': 'Tax Year (Optional)',
  'اختيار': 'Select',
  '✓ مختار': '✓ Selected',
  'تغيير الاختيار': 'Change Selection',
  'القيمة الإيجارية': 'Rental Value',
  'الضريبة السنوية': 'Annual Tax',
  'بيانات الربط الضريبي (لا يمكن تعديلها)': 'Tax Link Data (Cannot be edited)',
  'تقديم طلب جديد': 'Submit New Request',
  'تعديل طلب': 'Edit Request',
  'رفع المستندات الداعمة': 'Upload Supporting Documents',
  'تحديث المستندات': 'Update Documents',
  'اكتب هنا أسباب الاعتراض على القيمة الضريبية المحسوبة...': 'Write here the reasons for objecting to the calculated tax value...',
  'اختر الربط الضريبي أولاً': 'Select a tax link first',
  'إلغاء والعودة': 'Cancel and Go Back',
  'جاري التسجيل...': 'Registering...',
  'تسجيل الطعن': 'Register Appeal',
  'تم تسجيل الطعن بنجاح، وتم إضافة رسم الطعن على السجل': 'Appeal registered successfully, appeal fee added to record',
  'حدث خطأ أثناء تحميل بيانات الطعن': 'Error loading appeal data',
  'تعذر تحميل بيانات الطعن': 'Failed to load appeal data',
  'تم تحديث بيانات الطعن بنجاح': 'Appeal data updated successfully',
    'بيانات الطعن': 'Appeal Data',
  'اختر ربطاً ضريبياً أولاً': 'Select a tax link first',
  'تغيير الاختيار': 'Change Selection',
  'إجمالي النتائج:': 'Total Results:',
  'صفحة': 'Page',
  'من': 'of',
  'القيمة الإيجارية السنوية': 'Annual Rental Value',
  'الضريبة السنوية': 'Annual Tax',
  'سبب الطعن': 'Appeal Reason',
  'اختيار ربطاً ضريبياً أولاً': 'Select a tax link first',
  'اضافه':'add',
    'كود:': 'Code:',
  'حساب': 'Calculate',
  'إخفاء': 'Hide',
  'عرض': 'View',
  'وحدة': 'Unit',
  'تحديث': 'Refresh',
  'المساحة': 'Area',
  'العنوان': 'Address',
  'المالك': 'Owner',
  'الاستخدام': 'Usage',
  'الحالة': 'Status',
  'الإجراءات': 'Actions',
  'معتمد': 'Approved',
    'من': 'of',
  'صفحة': 'Page',
  'عنصر': 'item',
  'المهام':'Tasks',
  'تعديل':'edite',
  'كل الإجراءات':'All Actions',
  'عودة للرئيسية':'Return to main page',
  'السابق': 'Previous',
  'التالي': 'Next',
  'لا توجد عناصر': 'No items',
  'الصفحة الأولى': 'First page',
  'الصفحة الأخيرة': 'Last page',
  'مسح البحث': 'Clear search',
  'نسبة الملكية': 'Ownership %',
  'نوع العلاقة': 'Relationship Type',
  'طريقة العلاقة': 'Relationship Method',
  'لا يوجد مستأجرون مسجلون': 'No registered tenants',
    'معرّف الوحدة:': 'Unit ID:',
  'معرّف الوحدة غير صحيح': 'Invalid Unit ID',
  'يرجى إدخال سنة ضريبية صحيحة': 'Please enter a valid tax year',
  'القيمة الإيجارية لا يمكن أن تكون سالبة': 'Rental value cannot be negative',
  'شاشة التقدير الضريبي': 'Tax Estimation Screen',
  'بيانات الوحدة والعقار': 'Unit and Property Data',
  'المالك الأساسي': 'Primary Owner',
  'لا يوجد ملاك مسجلون لهذه الوحدة': 'No registered owners for this unit',
  'لا يوجد مستأجرون مسجلون لهذه الوحدة': 'No registered tenants for this unit',
  'إعدادات التقدير الضريبي': 'Tax Estimation Settings',
  'تقدير تلقائي إذا تُرك فارغاً': 'Auto-estimate if left empty',
  'نوع الاستخدام': 'Usage Type',
  'المسؤول عن السداد': 'Payer',
  'خطة السداد': 'Payment Plan',
  'دفع كامل': 'Full Payment',
    'لجنة الإعفاءات': 'Exemption Committee',
  'عرض جميع طلبات الإعفاء ومراجعة التوصيات قبل إرسالها للمدير.': 'View all exemption requests and review recommendations before sending to the manager.',
  'رقم الطلب': 'Request No.',
  'الممول': 'Taxpayer',
  'نوع الإعفاء': 'Exemption Type',
  'المستند': 'Document',
  'لا توجد طلبات إعفاء': 'No exemption requests',
  'معلقة للجنة': 'Pending Committee',
  'معروضة على المدير': 'Presented to Manager',
  'إصدار توصية': 'Issue Recommendation',
  'تم الإرسال': 'Sent',
  'توصية لجنة الإعفاء': 'Exemption Committee Recommendation',
  'العقار:': 'Property:',
  'توصية اللجنة': 'Committee Recommendation',
  'اختر...': 'Select...',
  'ملاحظات اللجنة': 'Committee Notes',
  'إرسال للمدير': 'Send to Manager',
  'يرجى اختيار توصية اللجنة': 'Please select a committee recommendation',
  'هل تريد إرسال توصية اللجنة للمدير للاعتماد النهائي؟': 'Do you want to send the committee recommendation to the manager for final approval?',
  'تم إرسال توصية اللجنة للمدير': 'Committee recommendation sent to manager',
  'الوحدة السكنية الأساسية': 'Primary Residential Unit',
  'إعفاء ذوي الإعاقة': 'Disability Exemption',
  'ملكيات وقفية': 'Endowment Properties',
  'جمعيات خيرية': 'Charities',
    'لجنة الطعون': 'Appeals Committee',
  'عرض جميع الطعون والمراجعة قبل إرسال التوصية إلى المدير.': 'View all appeals and review before sending the recommendation to the manager.',
  'رقم القضية': 'Case No.',
  'كود الوحدة': 'Unit Code',
  'المواطن': 'Citizen',
  'سبب الطعن': 'Appeal Reason',
  'لا توجد طعون': 'No appeals',
  'توصية لجنة الطعن': 'Appeal Committee Recommendation',
  'الوحدة:': 'Unit:',
  'الضريبة المقترحة بعد قبول الطعن': 'Proposed Tax After Accepting the Appeal',
  'عند قبول الطعن يجب تحديد الضريبة المقترحة': 'When accepting the appeal, the proposed tax must be specified',
  'تقسيط على دفعتين': 'Installment over 2 payments',
  'تفعّل تلقائياً — يوجد طعون مسجّلة': 'Auto-activated — Appeals registered',
  'جاري المعاينة...': 'Previewing...',
  'نتيجة المعاينة الضريبية': 'Tax Preview Result',
  'المالك المستخدم في الحساب': 'Owner used in calculation',
  'وصف الموقع / العقار': 'Location / Property Description',
  'صافي القيمة الإيجارية السنوية': 'Net Annual Rental Value',
  'إعفاء ضريبي': 'Tax Exemption',
  'رسوم الطعن': 'Appeal Fee',
  'إجمالي المستحق': 'Total Due',
  'قيمة القسط': 'Installment Amount',
  'دفعات': 'payments',
    'أهلاً بك في نظام المساعدة الذكي. كيف أساعدك اليوم؟': 'Welcome to the Smart Assistant system. How can I help you today?',
  'المعذرة، حدث خطأ أثناء معالجة الرد من السيرفر.': 'Sorry, an error occurred while processing the server response.',
  'المعذرة، سيرفر المساعد الضريبي غير متاح حالياً. يرجى التأكد من تشغيل السيرفر.': 'Sorry, the tax assistant server is currently unavailable. Please ensure the server is running.',
  'حدث خطأ غير متوقع في الواجهة.': 'An unexpected error occurred in the interface.',
  'مساعد النظام الذكي': 'System Smart Assistant',
  'متصل الآن للرد على استفساراتك': 'Online now to answer your queries',
  'اكتب استفسارك هنا...': 'Type your question here...',
  'جاري الرد...': 'Replying...',
  'الرئيسية': 'Home',
    'لوحة التحكم الموحدة': 'Unified System Dashboard',
  'نظرة عامة على المباني والوحدات والنشاطات الضريبية': 'Overview of buildings, units, and tax activity',
  'سجل النظام الشامل': 'Full System Log',
  'الوحدات الضريبية': 'Tax Units',
  'دور ': 'Floor ',
  'وحدة رقم:': 'Unit No.:',
  'مغلق': 'Closed',
  'بانتظار الرسم': 'Waiting for Fee',
  'قيد اللجنة': 'In Committee Review',
  'لا توجد طلبات.': 'No requests.',
  'لا توجد بيانات.': 'No data.',
    'مركز التحكم': 'Control Center',
  'تحكم في شكل النظام، اللغة، والتنبيهات مع أدوات حفظ وتصدير البيانات.': 'Manage appearance, language, alerts, backup, and exports.',
  'سجل محفوظ': 'saved records',
  'النسخ الاحتياطي والتصدير': 'Backup and Export',
  'احتفظي بنسخة كاملة أو صدّري الجداول الأساسية.': 'Keep a full backup or export the main tables.',
  'تنزيل ملف JSON يحتوي على بيانات النظام المحفوظة محليًا.': 'Download a JSON file with locally stored system data.',
  'إنشاء نسخة': 'Create Backup',
  'تصدير البيانات الأساسية في ملف CSV قابل للفتح في Excel.': 'Export main data as a CSV file for Excel.',
  'تصدير CSV': 'Export CSV',
  'العربية مفعلة الآن': 'Arabic is active',
  'تم إنشاء نسخة احتياطية بنجاح': 'Backup created successfully',
  'تم تصدير البيانات بنجاح': 'Data exported successfully',
  'النسخ الاحتياطي':'Backup',
  'تصدير البيانات':'Export',
  'تغيير اللغة والاتجاه لكل النظام.':'Change the language and direction for the entire system.',
  'تم الحساب باستخدام قيمة إيجارية مدخلة يدوياً.': 'Calculated using manually entered rental value.',
  'تم الحساب باستخدام التقدير التلقائي للقيمة الإيجارية.': 'Calculated using automatically estimated rental value.',
  'جاري الاعتماد...': 'Approving...',
  'اعتماد التقدير الضريبي': 'Approve Tax Estimation',
  'تأكيد الاعتماد': 'Confirm Approval',
  'هل أنت متأكد من اعتماد هذا التقدير الضريبي؟': 'Are you sure you want to approve this tax estimation?',
  'سيتم حفظ التقييم وإرسال الإشعار للجهة المعنية. لا يمكن التراجع عن هذا الإجراء.': 'The assessment will be saved and a notification sent. This action cannot be undone.',
  'نعم، اعتماد': 'Yes, Approve',
  'يجب تنفيذ معاينة الحساب أولاً قبل الاعتماد': 'You must run a calculation preview before approving',
  'حدث خطأ أثناء معاينة التقدير الضريبي': 'Error previewing tax estimation',
  'حدث خطأ أثناء اعتماد التقييم الضريبي': 'Error approving tax estimation',
  'لا توجد بيانات لهذه الوحدة': 'No data for this unit',
  'حدث خطأ أثناء تحميل بيانات الوحدة': 'Error loading unit data',
  'تم اعتماد التقييم الضريبي بنجاح ✓': 'Tax assessment approved successfully ✓',
    'جاري البحث عن الوحدة...': 'Searching for unit...',
  'لا توجد أقساط مستحقة حالياً (قد يكون النظام لم يولدها بعد).': 'No pending installments currently (the system may not have generated them yet).',
  'الأقساط المستحقة (الرجاء اختيار قسط للدفع)': 'Pending Installments (Please select an installment to pay)',
  'تاريخ الاستحقاق': 'Due Date',
  'المبلغ (ج.م)': 'Amount (EGP)',
  'بيانات الوحدة والمالك': 'Unit and Owner Data',
  'رقم الإصال (Receipt No)': 'Receipt No.',
  'اكتب رقم الكاشير...': 'Enter cashier number...',
  'مبلغ الدفع (ج.م)': 'Payment Amount (EGP)',
  'تاريخ السداد': 'Payment Date',
  'إجمالي الضريبة السنوية': 'Total Annual Tax',
  'رقم الإيصال:': 'Receipt No.:',
  'اسم المالك:': 'Owner Name:',
  'العنوان:': 'Address:',
  'المبلغ المدفوع:': 'Paid Amount:',
  'طريقة الدفع:': 'Payment Method:',
  'تاريخ السداد:': 'Payment Date:',
  'القسط:': 'Installment:',
  'طباعة الإيصال': 'Print Receipt',
  'العودة للرئيسية': 'Back to Main',
    'نوع الإجراء': 'Action Type',
  'بحث عن موظف': 'Search Employee',
  'ابحث بالاسم، الرقم القومي، أو كود الموظف...': 'Search by name, National ID, or employee code...',
  'لا توجد وحدة مطابقة لكود البحث' :'No unit matches the search code',
  'اختر الشارع...':'Select Street...',
  'اختر الحي...':'Select Neighborhood...',
    'بحث واختيار عقار': 'Search and Select Property',
  'من تاريخ': 'From date',
  'إلى تاريخ': 'To date',
  'تسجيل إعفاءات':'Recording Exemptions',
  'تسجيل طعن':'Recording Appeal',
  'المدير العام':'Manager General',
  'المراجع المالي':'Financial Reviewer',
  'مدير النظام':'System Administrator',
  'مسح': 'Clear',
  'لا توجد سجلات مطابقة.': 'No matching logs.',
  'الصفحة السابقة': 'Previous Page',
  'الصفحة التالية': 'Next Page',
  'لا توجد تفاصيل': 'No details',
  'تم إنشاء حساب جديد للموظف:': 'Created a new account for employee:',
  'تعديل حالة حساب الموظف:': 'Changed account status for employee:',
  'تم تعديل بيانات الموظف:': 'Updated employee data:',
  'تم حذف حساب الموظف:': 'Deleted employee account:',
  'نشط': 'Active',
  'معلق': 'Suspended',
  'نشاط': 'Activity',
  'النظام': 'System',
    'كود:': 'Code:',
  ' - ': ' - ',
  'تم إنشاء حساب جديد للموظف:': 'Created a new account for employee:',
  'تعديل حالة حساب الموظف:': 'Changed account status for employee:',
  'تم تعديل بيانات الموظف:': 'Updated employee data:',
  'تم حذف حساب الموظف:': 'Deleted employee account:',
  'إجمالي المستخدمين':'Total Users',
  'تعذر جلب بيانات الموظفين':'Unable to retrieve employee data',
  'بحث باسم أو الرقم القومي للموظف':'Search by employee Name/National ID',
  'سجل نظام التدقيق':'Aduit System Log',
    'إدارة حسابات الموظفين': 'Employee Account Management',
  'إضافة موظف جديد': 'Add New Employee',
  'بحث باسم أو الرقم القومي للموظف...': 'Search by employee name or National ID...',
  'كود الموظف': 'Employee Code',
  'المسمى الوظيفي': 'Job Title',
  'الصلاحية': 'Privilege',
  'حالة الحساب': 'Account Status',
  'تغيير الحالة': 'Change Status',
  'لا يوجد موظفين مطابقين للبحث.': 'No employees match the search.',
  'عذرا، تعذر تحديث حالة حساب الموظف في قاعدة البيانات.': 'Sorry, could not update the employee account status in the database.',
  'مدخل بيانات': 'Data Entry',
  'مُراجع': 'Reviewer',
  'مالي': 'Financial',
  'مدير مأمورية': 'District Manager',
  'لجنة الطعون': 'Appeals Committee',
    'حالة النظام': 'System Health',
  'ممتازة': 'Excellent',
  'أحدث العمليات المسجلة': 'Latest Recorded Operations',
  'إضافة حساب': 'Add Account',
  'تعديل حساب': 'Edit Account',
  'حذف حساب': 'Delete Account',
  'إقرار': 'Approve',
  'موضح بالتفاصيل': 'Detailed in logs',
  'إلى': 'to',
  'كل الصلاحيات': 'All Privileges',
  'كل المسميات': 'All Job Titles',
  'قائمة الموظفين': 'Employees List',
  'تعطيل': 'Disable',
  'تفعيل': 'Enable',
  'لا يوجد موظفين مطابقين للبحث أو الفلاتر.': 'No employees match the search or filters.',
  'عودة لجدول الموظفين': 'Back to Employees List',
  'المأمورية التابعة': 'Affiliated Office',
  'حفظ وإنشاء الحساب': 'Save & Create Account',
  'هل أنت متأكد من تعطيل هذا الموظف؟': 'Are you sure you want to disable this employee?',
  'هل أنت متأكد من تفعيل هذا الموظف؟': 'Are you sure you want to enable this employee?',
  'تأكيد وموافق': 'Confirm & Approve',
  'إلغاء الأمر': 'Cancel Action',
  'مثال: EMP-005': 'Example: EMP-005',
  '14 رقم': '14 digits',
  'مثال: مراجع ضرائب أول': 'Example: Senior Tax Reviewer',
  'مأمورية مدينة نصر - القاهرة': 'Nasr City Office - Cairo',
  'مأمورية الدقي - الجيزة': 'Dokki Office - Giza',
  'مأمورية الإسكندرية': 'Alexandria Office',
  'المركز الرئيسي': 'Main Center',
  'البيانات السابقة:': 'Previous Data:',
  'الاسم:': 'Name:',
  'كود الموظف:': 'Employee Code:',
  'رقم المنظومة:': 'System ID:',
  'إضافة موظف جديد': 'Add New Employee',
  'لا توجد عمليات مسجلة حالياً':'There are currently no recorded operations',
  'هذه الوحدة لم توافق عليها الإدارة بعد ولا يمكن تسجيل سداد أو طباعة فاتورة.': 'This unit has not been approved by management yet, cannot register payment or print invoice.',
  'وحدة غير موجودة برقم:': 'Unit not found with ID:',
  'الرجاء اختيار القسط المراد دفعه أولاً من الجدول': 'Please select the installment to pay from the table first',
  'تم تسجيل السداد بنجاح. يمكنك طباعة الإيصال الآن.': 'Payment registered successfully. You can print the receipt now.',
  'فشلت العملية:': 'Operation failed: ',
  'حدث خطأ في البحث': 'Error during search',
  'استخدم خانة البحث أعلاه لإدخال رقم الوحدة': 'Use the search box above to enter the unit number',
  'سيتم عرض بيانات الوحدة والأقساط المستحقة هنا.': 'Unit data and pending installments will be displayed here.',
  'جميع الأقساط المسجلة لهذه الوحدة تم دفعها': 'All installments registered for this unit have been paid.',
  'لا يوجد أقساط مستحقة': 'No pending installments',
  'جاهز للدفع': 'Ready to Pay',
  'إيصال سداد الضريبة': 'Tax Payment Receipt',
  'المالك الأساسي': 'Primary Owner',
  'رقم الوحدة': 'Unit ID',
    'أدخل رقم الوحدة للبحث السريع واضغط Enter...': 'Enter unit number for quick search and press Enter...',
  'تسجيل سداد ضريبي': 'Tax Payment Registration',
  'وحدة رقم:': 'Unit No.:',
  'لا توجد أقساط مستحقة': 'No pending installments',
  'نقدي (Cash)': 'Cash',
  'فوري (Fawry)': 'Fawry',
  'إنستا باي': 'InstaPay',
  'تأكيد دفع القسط (': 'Confirm installment payment (',
  'هل أنت متأكد من تسجيل مبلغ ': 'Are you sure you want to register an amount of ',
  'رقم الإيصال (Receipt No)': 'Receipt No.',
  'السنة الضريبية': 'Tax Year',
  'إجمالي المستحق': 'Total Due',
    'لوحة متابعة تشغيلية فورية': 'Instant Operational Dashboard',
  'عرض الكل': 'View All',
    'التقارير المالية والإدارية': 'Financial and Administrative Reports',
  'مؤشرات الأداء الرئيسية (KPIs)': 'Key Performance Indicators (KPIs)',
  'بانتظار الاعتماد': 'Pending Approval',
  'ملف': 'File',
  'نسبة التحصيل الكلية': 'Overall Collection Rate',
  'تم سداد': 'Paid',
  'قسط من إجمالي الأقساط': 'installments out of total installments',
  'تصدير التقرير PDF': 'Export PDF Report',
  'لا توجد بيانات أداء متاحة': 'No performance data available',
  'غير فعال': 'Inactive',
    'الاعتمادات': 'Approvals',
  'مراجعة الطعون والإعفاءات واتخاذ القرار النهائي': 'Review appeals and exemptions and make the final decision',
  'تعذّر تحميل البيانات. يرجى المحاولة مرة أخرى.': 'Failed to load data. Please try again.',
  'حدث خطأ أثناء إرسال القرار. يرجى المحاولة مرة أخرى.': 'An error occurred while sending the decision. Please try again.',
  'ضريبة اللجنة': 'Committee Tax',
  'لا توجد إعفاءات': 'No exemptions',
  'قرار': 'Decision',
  'تم البت': 'Decided',
  'كود الوحدة': 'Unit Code',
  'قرار المدير – الطعن': 'Manager Decision - Appeal',
  'قرار المدير – الإعفاء': 'Manager Decision - Exemption',
  'القرار': 'The Decision',
  'الضريبة النهائية المعتمدة': 'Final Approved Tax',
  'أدخل قيمة الضريبة المعتمدة': 'Enter the approved tax value',
  'نسبة الإعفاء (%)': 'Exemption Percentage (%)',
  'ملاحظة المدير': 'Manager Note',
  'أدخل ملاحظتك (اختياري)': 'Enter your note (optional)',
  'تأكيد القرار': 'Confirm Decision',
  'ينتظر قرار': 'Pending Decision',
  'بانتظار الحساب': 'Pending Calculation',
  'إرجاع للحساب': 'Revert to Calculation',
  'بحث باسم المالك...': 'Search by owner name...',
  'لا توجد وحدات مطابقة': 'No matching units',
  'جاري تحميل الوحدات...': 'Loading units...',
  'نتائج البحث عن:': 'Search results for:',
  'لا يوجد تقييم ضريبي مرتبط بهذه الوحدة': 'No tax assessment linked to this unit',
  'حذف التقييم الضريبي': 'Delete tax assessment',
  'إرجاع التقييم إلى انتظار الحساب': 'Revert assessment to pending calculation',
  'جرّب بحثاً مختلفاً أو امسح الفلتر': 'Try a different search or clear the filter',
  'لا توجد وحدات في هذه الحالة حالياً': 'There are no units in this state currently',
  'تعذر تحميل تفاصيل الوحدة': 'Failed to load unit details',
  'حدث خطأ أثناء تحميل الوحدات': 'Error loading units',
  'حدث خطأ أثناء حذف التقييم الضريبي': 'Error deleting tax assessment',
  'حدث خطأ أثناء إرجاع التقييم إلى انتظار الحساب': 'Error reverting assessment to pending calculation',
  'لا يمكن حذف التقييم لأن السنة الضريبية غير متوفرة لهذه الوحدة': 'Cannot delete assessment because tax year is not available for this unit',
  'هذا التقييم مرتبط بطعون. هل تريد حذف الطعون المرتبطة أيضاً؟': 'This assessment is linked to an appeal. Do you want to delete the linked appeals as well?',
  'مراجعة الضريبة العقارية': 'Real Estate Tax Review',
  'مراجعة الوحدات · حساب الضريبة · اعتماد التقدير وإرساله للمالية': 'Review units · Calculate tax · Approve assessment and send to finance',
};

const sortedPhraseEntries = Object.entries(phraseTranslations)
  .sort(([first], [second]) => second.length - first.length);

const translateArabicText = (text) => {
  return sortedPhraseEntries.reduce(
    (value, [arabic, english]) => value.split(arabic).join(english),
    text
  );
};

const restoreOriginalText = (node) => {
  if (node.nodeType === Node.TEXT_NODE && node.originalArabicText) {
    node.nodeValue = node.originalArabicText;
  }
};

const translateDomText = (root, lang) => {
  if (!root || typeof Node === 'undefined') return;

  const shouldSkip = (node) => {
    const parent = node.parentElement;
    return !parent || ['SCRIPT', 'STYLE', 'NOSCRIPT'].includes(parent.tagName);
  };

  const translateTextNode = (node) => {
    if (shouldSkip(node)) return;

    if (node.nodeValue !== node.lastTranslatedValue) {
      node.originalArabicText = node.nodeValue;
    }

    const original = node.originalArabicText;
    if (!original) return;
    const trimmed = original.trim();
    if (!trimmed) return;

    if (lang === 'ar') {
      if (node.nodeValue !== original) {
        node.nodeValue = original;
      }
      node.lastTranslatedValue = original;
      return;
    }

    const nextValue = translateArabicText(original);
    if (node.nodeValue !== nextValue) {
      node.nodeValue = nextValue;
    }
    node.lastTranslatedValue = nextValue;
  };

  const translateAttribute = (element, attribute) => {
    const lastTranslatedAttr = `data-last-translated-${attribute}`;
    const original = element.getAttribute(attribute);
    if (!original) return;

    if (original !== element.getAttribute(lastTranslatedAttr)) {
      element.setAttribute(`data-original-${attribute}`, original);
    }

    const originalVal = element.getAttribute(`data-original-${attribute}`);
    if (!originalVal) return;

    if (lang === 'ar') {
      if (element.getAttribute(attribute) !== originalVal) {
        element.setAttribute(attribute, originalVal);
      }
      element.setAttribute(lastTranslatedAttr, originalVal);
      return;
    }

    const nextValue = translateArabicText(originalVal);
    if (element.getAttribute(attribute) !== nextValue) {
      element.setAttribute(attribute, nextValue);
    }
    element.setAttribute(lastTranslatedAttr, nextValue);
  };

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while (node) {
    translateTextNode(node);
    node = walker.nextNode();
  }

  root.querySelectorAll('[placeholder], [title], [aria-label]').forEach((element) => {
    ['placeholder', 'title', 'aria-label'].forEach((attribute) => {
      if (element.hasAttribute(attribute)) {
        translateAttribute(element, attribute);
      }
    });
  });
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const savedLang = localStorage.getItem('tax_lang');
    return savedLang || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('tax_lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;

    let bootstrapLink = document.getElementById('bootstrap-theme');
    if (!bootstrapLink) {
      bootstrapLink = document.createElement('link');
      bootstrapLink.id = 'bootstrap-theme';
      bootstrapLink.rel = 'stylesheet';
      document.head.insertBefore(bootstrapLink, document.head.firstChild);
    }
    bootstrapLink.href = lang === 'ar' ? '/bootstrap.rtl.min.css' : '/bootstrap.min.css';
  }, [lang]);

  useEffect(() => {
    const root = document.getElementById('root');
    translateDomText(root, lang);

    const observer = new MutationObserver(() => {
      window.requestAnimationFrame(() => translateDomText(root, lang));
    });

    if (root) {
      observer.observe(root, { childList: true, subtree: true, characterData: true });
    }

    return () => observer.disconnect();
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key) => translations[lang][key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, translations, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);