// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data;

#nullable disable

namespace Persistance.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.DomainLayer.Entities.AdminModule.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.AdminModule.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(1879),
                            GovernorateId = 1,
                            Name = "مدينة نصر"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2835),
                            GovernorateId = 1,
                            Name = "المعادي"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2837),
                            GovernorateId = 1,
                            Name = "حلوان"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2839),
                            GovernorateId = 2,
                            Name = "الدقي"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2841),
                            GovernorateId = 2,
                            Name = "الهرم"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2843),
                            GovernorateId = 3,
                            Name = "سيدي جابر"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2844),
                            GovernorateId = 3,
                            Name = "العجمي"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2846),
                            GovernorateId = 4,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2848),
                            GovernorateId = 4,
                            Name = "البداري"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2850),
                            GovernorateId = 4,
                            Name = "ديروط"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2852),
                            GovernorateId = 4,
                            Name = "القوصية"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2853),
                            GovernorateId = 5,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2855),
                            GovernorateId = 6,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(2857),
                            GovernorateId = 7,
                            Name = "قنا"
                        });
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(7286),
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8238),
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8240),
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8242),
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8244),
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8245),
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 963, DateTimeKind.Utc).AddTicks(8247),
                            Name = "قنا"
                        });
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Neighborhoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(5962),
                            Name = "الحي السابع",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 2,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(7117),
                            Name = "الحي الثامن",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 3,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(7120),
                            Name = "الحي العاشر",
                            Zone = "C"
                        },
                        new
                        {
                            Id = 4,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(7122),
                            Name = "غرب البلد",
                            Zone = "A"
                        },
                        new
                        {
                            Id = 5,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(7123),
                            Name = "شرق البلد",
                            Zone = "B"
                        },
                        new
                        {
                            Id = 6,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(7125),
                            Name = "الأربعين",
                            Zone = "C"
                        });
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildYear")
                        .HasColumnType("int");

                    b.Property<string>("BuildingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentPropertyNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<string>("OldPropertyNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanningNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Streets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4107),
                            Name = "شارع النصر"
                        },
                        new
                        {
                            Id = 2,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4897),
                            Name = "شارع عباس العقاد"
                        },
                        new
                        {
                            Id = 3,
                            CenterId = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4899),
                            Name = "شارع مكرم عبيد"
                        },
                        new
                        {
                            Id = 4,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4901),
                            Name = "شارع الجمهورية"
                        },
                        new
                        {
                            Id = 5,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4902),
                            Name = "شارع الهلالي"
                        },
                        new
                        {
                            Id = 6,
                            CenterId = 8,
                            CreatedAt = new DateTime(2026, 6, 21, 19, 2, 51, 965, DateTimeKind.Utc).AddTicks(4904),
                            Name = "شارع يسري راغب"
                        });
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SharePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UnitId");

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Center", b =>
                {
                    b.HasOne("Core.DomainLayer.Entities.Governorate", "Governorate")
                        .WithMany("Centers")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Neighborhood", b =>
                {
                    b.HasOne("Core.DomainLayer.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Street", b =>
                {
                    b.HasOne("Core.DomainLayer.Entities.Center", "Center")
                        .WithMany("Streets")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Unit", b =>
                {
                    b.HasOne("Core.DomainLayer.Entities.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RoleAssignment", b =>
                {
                    b.HasOne("Owner", "Owner")
                        .WithMany("Assignments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.DomainLayer.Entities.Property", "Property")
                        .WithMany("Assignments")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.DomainLayer.Entities.Unit", "Unit")
                        .WithMany("Assignments")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("Property");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Center", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Governorate", b =>
                {
                    b.Navigation("Centers");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Property", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Core.DomainLayer.Entities.Unit", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Owner", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
